Fix JENKINS-68930 Java17 Error on slave start
jenkinsci/envinject-plugin pull request #206
Opened 2022-07-05 11:41 UTC by bulanovk

Use WA to work with modifiers field filtered since JDK12.
--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED are required.

2022-07-05 13:15 UTC, NotMyFault commented
Untested, but looks good so far. Thanks for filing the PR!

2022-07-05 14:13 UTC, oleg-nenashev requested changes
Thanks for the fix! It will likely fail SpotBugs, because the return value of the new method might be null. In the end you should check for null and throw `NoSuchMethodException` to retain the behavior

2022-07-13 06:19 UTC, bulanovk commented
Any chance to get this PR merged?

2022-07-26 20:09 UTC, NotMyFault approved these changes
Looks good, do you mind taking another look @oleg-nenashev ?

2022-07-26 20:56 UTC, limeman40 commented
Can someone review the change request so this could possibly be merged?

2022-07-27 13:31 UTC, limeman40 commented
@oleg-nenashev Can you please review this so it can possible get merged?

2022-08-01 08:21 UTC, merged